version: '3.8'
services:
  db:
    image: mysql:8.0.37
    command: --bind-address=0.0.0.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
    container_name: mysql
    networks:
      - prom-network
networks:
  prom-network:
    driver: bridge
